name: Build Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        
      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: 安装 pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: 获取 pnpm store 目录
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
          
      - name: 设置 pnpm 缓存
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
            
      - name: 安装依赖
        run: pnpm install
        
      - name: 构建应用
        run: pnpm build
        
      - name: 测试打包 (macOS)
        if: matrix.os == 'macos-latest'
        run: pnpm pack
        
      - name: 测试打包 (Windows)
        if: matrix.os == 'windows-latest'
        run: pnpm pack
